name: Build WebUI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 设置 Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: 构建 WebUI
        run: |
          bun install
          bun run build

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: puniyu-webui
          path: dist
